### ISSUE TITLE
 code for food-delivery-website

### ISSUE THREAD

**Issue by hariom20singh** [hariom20singh/food-delivery-website#12]

**Comment by aanchalsharmaa1024** [comment]
I can do it . pls assign it to me

**Comment by aanchalsharmaa1024** [comment]
Could I take time of 3-4 days?

**Comment by shaziaah19** [comment]
HELLO, I want to contribute please assign this to me

**Comment by Rohans-7** [comment]
Hey @hariom20singh can you please assign this issue to me. I really want to contribute and it will be a good first issue for me.
Thank you !!! Regards.

**Comment by deepti-29** [comment]
Hello sir,
Can you assign me this?
