### ISSUE TITLE
submit code for hacktoberfest

### ISSUE THREAD

**Issue by hariom20singh** [hariom20singh/food-delivery-website#13]

**Comment by Esha-in-arena** [comment]
hey @hariom20singh  i want to contribute to your repo.  kindly assign this to me.

**Comment by Esha-in-arena** [comment]
I can submit code in any language?

**Comment by ArcheR1901** [comment]
hey @hariom20singh I have some basic java codes which I would like to contribute. Please assign me this piece of work if it is valid for this repository.

**Comment by priyanshuanand166** [comment]
Assign this to me as i am well versed in dsa and i am pretty confident that you will like my merge request.

**Comment by nilesh080802** [comment]
I want to contribute please assign me this issue
