### ISSUE TITLE
I want js code for food delivery website

### ISSUE THREAD

**Issue by hariom20singh** [hariom20singh/food-delivery-website#3]
if you good at java script then help in developing food website

**Comment by chimoski** [comment]
I want to take this up , Kindly assign it to me please

**Comment by himanshu17-2000** [comment]
please can you assign this to me , i can use  MERN stack in this issue

**Comment by chimoski** [comment]
@himanshu17-2000  let's work on this together, you can work on the Backend while I do the frontend

**Comment by hariom20singh** [comment]
I already started frontend... I want backend developer

**Comment by chimoski** [comment]
oh, that's great, I would have suggested we use MERN stack for the project instead of vanilla js and php

**Comment by hariom20singh** [comment]
ok.

**Comment by chimoski** [comment]
so what is next? we should go ahead with MERN?
